### PR TITLE
Features/mobile friendly 142

### PR DESCRIPTION
**Pull request by djarredon**
Checklist of pages to test during code review

- [x] Home page
- [x] Professional profile view
- [ ] Professional edit page
- [x] Organization profile view
- [x] Organization edit page
- [x] Program profile page
- [x] Program edit page
- [x] Search results page
- [x] About page
- [x] Navbar hamburger menu (when signed in, signed out, and as admin)

**Note:** The admin page is not mobile friendly, and will not be.
**Note 2, This Time it's Personal:** Pay special attention to the MESA logo in the navbar on different screen sizes. Not because it's particularly problematic, but because I made three of them and am proud of the result :smile:

### CODE REVIEW

**Review by Domicilius — APPROVED** [review]

**Review by iandusenbury — APPROVED** [review]

**Comment by iandusenbury** [comment]
will merge once conflicts are resolved

**Review by halalak — APPROVED** [review]

**Review by mballeza — CHANGES_REQUESTED** [review]
First of all, solid work on everything! Looks great. I've viewed all of the pages on the checklist at 320px width.
Here's what I found:

- Program profile page
  - Text ~~pushes extra space~~ extends the width of the page on the right ~~from~~ if the  address/contact url is too long.
- ~~Professional edit page~~
  - ~~Not exactly related to the mobile friendly branch, but still has the extra white space to the right of the paper components.~~
- Search results page
  - Change the address shown to just address line 1 so the contact button can fit and remove redundancy in address contents. **Edit: Right now the full address is stored in the addressLine1 variable.**

**Comment by djarredon** [comment]
Took a little while to figure out number 2, but all the comments have been addressed.

**Review by mballeza — APPROVED** [review]

**Comment by mballeza** [comment]
Actually, needs a little more work on the professional edit page, just the couple issues we talked about on slack

**Review by Domicilius — APPROVED** [review]

**Pull request merged**
